### ISSUE TITLE
Fix Typo in class name

### ISSUE THREAD

**Issue by fiedsch** [do-while/contao-pdf-nc-attachment-bundle#1]
Fix Typo:
Umbenennen von src/Resources/contao/classes/pdfNcAttachm**a**ntHooks.php
(e anstelle a) und dazu passend

https://github.com/do-while/contao-pdf-nc-attachment-bundle/blob/f8fed6f98f3b0f38633f298f3f22b615bf2f7157/src/Resources/contao/config/config.php#L22

anpassen

**Comment by do-while** [comment]
Sowas sieht man als Entwickler nicht selbst :-)
Ich bin aber beruhigt, dass sowohl die Klasse, als auch der Aufruf falsch geschrieben ist.
Die Änderung ist sicherlich nicht sooo eilig.

**Comment by fiedsch** [comment]
Ein Bug in dem Sinn ist es ja nicht, denn die klasse kann ja heißen, wie sie will. Hatt emicht nur irritiert und ich dachte, daß es bestimmt nicht Absicht war.

**Comment by do-while** [comment]
Ist "verbessert"
