### ISSUE TITLE
Can not install - Contao 4.13, php8.1

### ISSUE THREAD

**Issue by Werbeagentur-Kopfnuss** [do-while/contao-pdf-nc-attachment-bundle#12]
Can not install pdf attachment in clean installation:

```
> Resolving dependencies using Composer Cloud v3.5.1

[7.2MiB/0.19s] Loading composer repositories with package information
[68.2MiB/8.82s] Updating dependencies
[86.8MiB/9.02s] Your requirements could not be resolved to an installable set of packages.
[86.8MiB/9.02s] 
  Problem 1
    - Conclusion: don't install do-while/contao-pdf-nc-attachment-bundle 2.8.10 (conflict analysis result)
    - Root composer.json requires do-while/contao-pdf-nc-attachment-bundle ^2.8 -> satisfiable by do-while/contao-pdf-nc-attachment-bundle[2.8.0, ..., 2.8.10].
    - do-while/contao-pdf-nc-attachment-bundle[2.8.0, ..., 2.8.8] require terminal42/notification_center ^1.4 -> satisfiable by terminal42/notification_center[1.7.0, 1.7.1].
    - terminal42/notification_center[1.7.0, ..., 1.7.1] require codefog/contao-haste ^5.0 -> satisfiable by codefog/contao-haste[5.0.0, ..., 5.0.16].
    - Conclusion: don't install codefog/contao-haste 5.0.16 (conflict analysis result)

[86.8MiB/9.02s] Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.
[38.6MiB/9.05s] Memory usage: 38.63MB (peak: 190.92MB), time: 9.06s.
[38.6MiB/9.05s] Finished Composer Cloud resolving.


# Cloud Job ID aZHTrIJySUPvSOzCoIlzYSDQJOs3oeVMv9DlmjFJyllzM2OrNFTY1fJYquva8FJ2QqAvYmzBEKAxUeQxfWzayrv10hJ0hK failed
```

Ich möchte einen Kundenseite aktualisieren, leider bekomme ich die Erweiterung nicht installiert und erhalte oben gezeigten Fehler.

Vielleicht besteht das Problem auch mit Contao Haste5.
In einer Installation mit Contao 4.13, php8 und NC 1.6 welches Contao Haste4 verwendet, kann ich die Erweiterung installieren.

**Comment by proplab** [comment]
Leider ist das keine Lösung, weil andere Anwendungen, die mit contao-pdf-nc-attachment-bundle zusammenspielen sollen, Notification-Center 1.7 und Haste 5.0. verlangen. Selbst Contao 4.13* tut das. 
Wäre es nicht doch möglich, da etwas zu tun? Kunde hat die Erweiterung gestern gekauft und jetzt können wir sie nicht verwenden.

**Comment by do-while** [comment]
Soweit ich weiß, ist Haste 5.0 erst ab Contao 5.0 einsetzbar, vorher wird das Notification-Center ^1.6 installiert, was eine ältere Version von Haste verwendet. Solange Sie mit Contao 4.13.x arbeiten, sollte die Erweiterung normal funktionieren, ich setze das selbst in mehreren Installationen so ein (PHP 8.0 bzw. 8.1).
Für Contao 5 ist die Erweiterung noch nicht freigegeben, da kann ich auch noch keinen Termin nennen, evtl. erst zur ersten 5er LTS.

Was genau funktioniert denn nicht zusammen mit dem Notification-Center ^1.6?

**Comment by proplab** [comment]
Zunächt mal vielen Dank für Ihre schnelle Antwort.
Wenn ich Contao 4.13.x (LTS neueste Version) habe und das Notification Center installiere, bekomme ich ohne spezifische Angaben NC 1.7 und Haste 5.0. Versuche ich das downzugraden, meckert z.B. con4gis-Reservation. Alles schon getestet.
Auf der Projektseite von NC sieht das auch so aus:
![Unbenannt](https://user-images.githubusercontent.com/6940747/222081357-80160eea-ce48-476e-8b9d-ea149529f76f.PNG)
Wenn ich contao-pdf-nc-attachment-bundle in ein frisches Contao 4.13.x ohne NC installiere, funktioniert es. Die passende NC-Version wird nachgezogen (taucht merkwürdigerweise aber nicht im Manager auf). Das ist aber wohl oft kein gangbarer Weg, wenn das NC schon vorhanden ist und vielfältig im Einsatz.

**Comment by do-while** [comment]
Man könnte probeweise den haste-Eintrag in der composer.json der Erweiterung rausnehmen. Haste wird ja trotzdem vom NC required. Dann würde NC die passende Version definieren. Meine Erweiterung wird sicherlich auch mit der aktuellen haste-Version zurecht kommen.
Wenn ich dazu komme, setze ich heute Abend eine Testinstallation auf und probiere das mal aus.

**Comment by proplab** [comment]
Das wäre wunderbar und würde mir sehr helfen. Grundsätzlich finde ich Ihre Erweiterung ganz ausgezeichnet und würde sie dringend brauchen.

**Comment by do-while** [comment]
So einfach ist es doch nicht, in Haste 5 sind einige Routinen aufgeräumt worden und die Aufrufe bzw. Namespaces haben sich geändert. Meine Anpassungen sind also etwas mehr als nur die 5 zuzulassen.
Ich werde die Änderung für das nächste Wochenende einplanen.

**Comment by proplab** [comment]
Ich bin begeistert. Vielen Dank!

**Comment by Werbeagentur-Kopfnuss** [comment]
> So einfach ist es doch nicht, in Haste 5 sind einige Routinen aufgeräumt worden und die Aufrufe bzw. Namespaces haben sich geändert. Meine Anpassungen sind also etwas mehr als nur die 5 zuzulassen. Ich werde die Änderung für das nächste Wochenende einplanen.

Danke, das ist mega!

**Comment by do-while** [comment]
Die neue Version 2.8.11 kann jetzt mit Haste 4.x und 5.x umgehen.
