### ISSUE TITLE
PDF-Seite nur ausgeben, wenn entsprechendes Formularfeld ausgefüllt/aktiviert

### ISSUE THREAD

**Issue by FlorinvV** [do-while/contao-pdf-nc-attachment-bundle#14]
Hallo Hagen,

eine kleine Frage dazu, inwiefern man PDF-Seiten an Bedingungen knüpfen kann:

Meine Situation ist die Folgende: Ich habe ein Formular, in dem man bis zu 10 mal Technische Daten mit optionalen Bild angeben kann. Diese Daten werden dann auf eine eigene Seite des PDFs geschrieben, weil ich dabei nicht ganz sagen kann, wie viel die Leute an Daten eingeben, soll das optionale Bild immer auf die nächste Seite der dazugehörigen Daten. 

Die PDF-Positionen der Daten und Bilder werden nur ausgegeben, wenn man diese auch aktiviert. Dazu habe ich für jedes mal Daten und für deren Bilder jeweils eine eigene Checkbox angelegt (Diese steuert über cond-form-fields auch die Ausgabe im Formular selbst). 

Jetzt zu meinem Problem: 
Es dürfen nur die Seiten angezeigt werden, auf denen tatsächlich Daten stehen. Soweit ich das verstanden habe, hilft mir das deaktivieren von "Alle gültigen Vorlagenseiten übernehmen" nicht, da den Seiten Positionen zugewiesen sind, auch wenn diese 
wegen Ihrer Bedingung nicht ausgegeben werden.

Die "Mehrformular-Vorlage" stößt hierbei auch an Ihre Grenzen, da ich ja nicht angeben kann "Wenn Bild-1 aktiviert dann füge Seite 2 ein", "Wenn Bild-2 aktiviert dann füge Seite 4 ein" usw., sondern nur "Wenn Bild-1 dann nutze Seiten 1-2", "Wenn Bild-2 dann nutze Seiten 1,3-4". 
Hier scheinen auch keine und/oder Abfragen möglich zu sein, oder? Sonst könnte ich im schlimmsten Fall auch einfach alle Fälle abgehen... 

Ich bräuchte im Grunde also eine "verbesserte" Version von "alle gültigen Vorlagenseiten übernehmen" die nicht nur darauf schaut, ob es Positionen gibt, die für Seiten angegeben wurden, sondern auch, ob deren Bedingungen auch erfüllt sind.

Ich hoffe, dass war einigermaßen verständlich und du kannst dazu irgendwie helfen, ich denke so eine Funktion wäre auch für andere hilfreich.

Vielen Dank für deine Mühe
LG Florin

**Comment by do-while** [comment]
Hallo,
das sollte doch genau mit der Mehrformular-Vorlage gehen. Diese Bedingungen nehmen keine Rücksicht auf Positionen der Seiten, sondern schließen nicht passende Seiten aus.
Hier kann man mehrere Zeilen angeben,
Bild 1 aktiviert => 1-2
Bild 2 aktiviert => 1,3-4
Sind dann beide Bilder ausgewählt, dann sollten nach den Bedingungen die Seiten 1-4 aktiv sein.

"Alle gültigen Vorlagenseiten übernehmen" ist z.B. dafür da, wenn an einem ausgefüllten Formular immer noch 2 Seiten AGBs o.ä. in der Vorlage dranhängen, die mit ausgegeben werden sollen. Aber auch dafür gelten die Mehrformular-Bedingungen.

Gruß, Hagen

**Comment by FlorinvV** [comment]
Hallo Hagen,

tut mir Leid, beim ersten mal testen hatte ich wohl etwas falsch gemacht, sodass es sich nicht richtig verhalten hat...
Ich habe es noch neu aufgebaut, jetzt tut es...

Vielen Dank für die Antwort und deine Zeit
LG Florin

**Comment by do-while** [comment]
Kein Problem
