### ISSUE TITLE
Farbwerte für einzelne Textfelder überschreiben.

### ISSUE THREAD

**Issue by swinde** [do-while/contao-pdf-nc-attachment-bundle#16]
Hallo Hagen,

mein Kunde wünscht sich, für einzelne Textfelder eine andere Schriftfarbe. 
```
Beispiel:
formlabel_feld1:  form_feld1
```
Wobei nur form_feld1 in Blau ausgegeben werden soll. Alles andere in Standardfarbe

Zur Zeit kann man nur für eine Zeile die Standardfarbe überschreiben.

**Comment by do-while** [comment]
Hallo,
was Kunden immer so wollen.

Da sehe ich nur die Möglichkeit, 2 Positionen anzulegen. Möchte der Kunde nicht sowieso die form_feld1-Ausgaben alle schön an einer Tab-Position untereinander? Für jeden Textteil einer Position noch eine Farbe möglich zu machen, halte ich für sehr überladen. Es ist jetzt schon erklärungsbedürftig, wie eine Position dort zusammengebaut wird.

Ich hätte jetzt auch gedacht, dass die Labels bereits in der Vorlage stehen und nur noch die Eingaben übernommen werden. Aber das kann je nach Anforderung natürlich anders aussehen.
In der aktuellen Version ist jetzt die Möglichkeit von relativen Positionsangaben hinzugekommen (siehe Handbuch), vielleicht kannst Du damit punkten.

**Comment by swinde** [comment]
[Wartungsbericht - SBR-Anlagen.pdf](https://github.com/do-while/contao-pdf-nc-attachment-bundle/files/13726188/Wartungsbericht.-.SBR-Anlagen.pdf)
Vielleicht habe ich das alles zu kompliziert aufgebaut! Das mit der Textfarbe werde ich dem Kunden ausreden.
Die absolute Positionierung ist eine schöne Sache, das würde vieles vereinfachen. Funktioniert nur leider nicht, wenn man 2 Positionen nebeneinander hat. Siehe Pdf im Anhang. Auf der 2 Seite habe ich das benutzt, da geht es, da jede Position die volle Seite einnimmt.

Ich wünsche Ihnen frohe Feiertage!

**Comment by do-while** [comment]
Die Erweiterung basiert auf der Idee, ein Formular (Beispiel: Steuerformular) mit den Online-Eingaben auszufüllen. Dann braucht man die Labeltexte nicht, da sie in der Vorlage bereits drin stehen. Die Positionen sind völlig frei positionierbar, auch mehrere Einzelpositionen in einer Zeile. Die Reihenfolge der Positionen spielt eigentlich keine Rolle, sie kann von oben nach unten sein, kann aber auch erst die linke, dann die rechte Spalte sein. Das ist vielleicht interessant bei der neuen alternativen relativen Positionierung.

Ein Beispiel aus meinem Vortrag (nur die blauen Einträge sind Positionen, alles andere ist in der Vorlage enthalten):
https://www.softleister.de/vortraege/pdf-erstellung.html#/7/1

**Comment by swinde** [comment]
Wie schon geschrieben habe ich das ganze etwas falsch aufgebaut.
Meine Anfrage kann geschlossen werden!

**Comment by do-while** [comment]
Wenn Du nicht weiterkommst, kannst Du Dich gern wieder melden, ggf. auch direkt per Mail.
