### ISSUE TITLE
Formularwerte mit der Zahl Null werden ignoriert

### ISSUE THREAD

**Issue by swinde** [do-while/contao-pdf-nc-attachment-bundle#18]
Hallo ich habe für einen Kunden ein Formular erstellt. Hier trägt er Werte für einen Wartungsbericht ein.

Einige Werte möchte ich nur anzeigen, wenn der jeweilige Feld auch ausgefüllt ist. Dafür benutze ich das Feld "Bedingung".
Das Programm ignoriert hier aber die Bedingung, wenn als Wert eine 0 eingetragen wird. Behelflösungen wie Null oder 0,0 funktionieren als Wert.

Der Feldtyp im Formular ist ein normales Textfeld.

Steffen Winde

**Comment by do-while** [comment]
Ich habe das Problem mit 0 in den Bedingungen gefunden und gefixt.
Bitte auf die neue Version updaten.

**Comment by swinde** [comment]
Wenn die Änderungen in der v2.10.2 enthalten sein sollte, kann ich die nicht laden. Version 2.10.1 wird als neueste angezeigt.
Contao 4.13.49

**Comment by do-while** [comment]
Das sollte aber drin sein. Wenn ich in die Erweiterungsliste rein gehe, ist die Version auch aufgeführt:

![image](https://github.com/user-attachments/assets/b76c5f8a-d0e5-4c17-95dd-5412ef065e3c)

Vielleicht musst Du einfach im Contao-Manager "Aktualisieren" wählen, dann sollte eigentlich die 2.10.2 installiert werden. Die Randbedingungen und Abhängigkeiten haben sich nicht verändert.

**Comment by swinde** [comment]
Ich kann schon die Version 2.10.1 laden. Hier scheint ein Versionskonflikt mit codefog/haste zu geben.
Ich muss composer, mit einer festeingestellten Version 2.10.2, zwingen diese zu installieren.

```
[33.2MiB/12.36s] Lock file operations: 0 installs, 2 updates, 0 removals
[33.2MiB/12.36s]   - Downgrading codefog/contao-haste (5.2.8 => 5.1.17)
[33.2MiB/12.36s]   - Upgrading do-while/contao-pdf-nc-attachment-bundle (2.10.0 => 2.10.2)
```
![image1](https://github.com/user-attachments/assets/cf56ff8d-a8d3-450f-a2ef-84af596b9c61)

**Comment by do-while** [comment]
Das verstehe ich jetzt nicht, weil codefog/contao-haste ab 5.2 auch in der 2.10.1 als Konflikt eingetragen war.

Ich sehe aber gerade, daß Du von 2.10.0 updatest, da waren die Konflikte noch nicht definiert, es gibt aber eine Unverträglichkeit mit Notification-Center ab 2.0 und da hängt contao-haste mit dran. Mit contao-haste 5.1 sollte es aber funktionieren.

**Comment by swinde** [comment]
Das ist der Punkt:
Wenn ich die Versionsauswahl auf ^2.10 stelle, installiert Composer wieder die Version 2.10.0 

`[33.2MiB/13.49s] Lock file operations: 0 installs, 2 updates, 0 removals
[33.2MiB/13.49s]   - Upgrading codefog/contao-haste (5.1.17 => 5.2.8)
[33.2MiB/13.49s]   - Downgrading do-while/contao-pdf-nc-attachment-bundle (2.10.2 => 2.10.0)`

**Comment by do-while** [comment]
Ja, da war der Konfikt noch nicht eingetragen. Damit sind dort alle Bedingungen erfüllt. Bei der Entscheidung zu contao-haste 5.2 bleibt die 2.10.2 auf der Strecke. Würde der Composer sich erst für diese Erweiterung entscheiden, bleibt bei Haste dann nur die 5.1.
Den Konfikt kann ich leider nicht rückwirkend eintragen, er besteht aber auch bei der 2.10.0, ist nur nicht abgesperrt.

**Comment by swinde** [comment]
terminal24/leads ist verantwortlich für contao-haste 5.2, wenn ich das Plugin deinstalliere kann ich auf 2.10.2 updaten.

**Comment by do-while** [comment]
Da sich aber bei der Installation von der Erweiterung nur contao-haste "down-gegraded" hat, bedeutet das für mich, dass Leads auch mit der 5.1 klar kommt, sonst hätte der Composer auch von Leads eine ältere Version installiert.

**Comment by swinde** [comment]
Ich lass das jetzt erst einmal so, vielen Dank für deine Anpassung. 
Der Contao Manager ist immer noch der Meinung, dass Version 2.10.1 die aktuellste Version ist!?

VG Steffen Winde

**Comment by do-while** [comment]
Das muss dann andere Gründe haben. Bei mir sieht es so aus:
![image](https://github.com/user-attachments/assets/8977393c-be58-4223-87f1-0c405c2f552f)

... und nach dem Update so:
![image](https://github.com/user-attachments/assets/cb698cf4-49cb-4a41-ab22-227366016b6a)

(Habe allerdings kein Leads dabei)
