### ISSUE TITLE
Pdf Generierung per email oder TestPDF Fehler wenn zweites Bild ab Seite 3

### ISSUE THREAD

**Issue by sfx12** [do-while/contao-pdf-nc-attachment-bundle#2]
Einen kleinen Bug entdeckt,

wenn man ein zweites Bild auf **Seite 3 einfügen** möchte, wird es auf **Seite 2** angezeigt. Beim "debugging" ist mir aufgefallen wenn ich die Position dieses Bildes auf Seite 4 Setze, wird es mir korrekt auf Seite 3 angezeigt, die PDF enthält dann jedoch **4 Seiten** und die 4. ist dann eine Blanko kopie der Seite 3!

**Comment by do-while** [comment]
Ich kann leider den Bug nicht nachstellen. Was ich auch mache, die Bilder landen auf der richtigen Seite.

- Ist der Effekt auch im "Download Test-PDF" zu beobachten?
- Ist das Bild evtl. zu groß angegeben?
- Verwendest Du die HOOKS, um das Bild zu positionieren?

Eigentlich geht das nicht, denn im Quellcode werden die Positionen seitenweise gelesen und ausgegeben, dann erst die nächste Seite. Wie dabei ein Bild auf die vorige Seite geraten soll, ist mir erstmal rätselhaft.

**Comment by sfx12** [comment]
1. Ja auch in der Test PDF ist das Bild auf Seite 2, anstatt 3
2. Bild hat exact die gleiche Größe wie ersteres (wird korrekt positioniert auf Seite 1)
3. Hooks ? Denke nicht, ich positioniere es einfach in den Einstellungen mit X/Y - Siehe Anhang...

![grafik](https://user-images.githubusercontent.com/16244014/65373991-10ac5000-dc85-11e9-8269-b378dc100681.png)

**Comment by do-while** [comment]
Das verstehe ich nicht, warum das so ist, ich kann es nicht nachvollziehen.
Wenn Du einzelne Positionen davor abschaltest, springt es dann immer noch auch die Vorseite?

Könntest Du mir vielleicht von allen Positionen einen Screenshot zumailen, damit ich das 1:1 nachbauen kann? Gern per E-Mail an info (ät) softleister.de

**Comment by sfx12** [comment]
![Screenshot_2019-09-23-Gateways-›-generierte-PDF---Contao-Open-Source-CMS](https://user-images.githubusercontent.com/16244014/65412667-0195e100-ddf0-11e9-9c1e-13210b65b411.jpg)

Einzelne Positionen davor abschalten brachte irgendwie auch nichts.

**Comment by do-while** [comment]
Verschiebe doch mal das 2. Unterschriftenelement (Seite 4) hinter die Seite 3, also an das Ende. Hilft das weiter?

**Comment by sfx12** [comment]
Tatsächlich, verschieben ging nicht (beim neuladen, ladete es auf gleicher Position wieder) habe jedoch eine neue Position erstellt und das Bild an letzter Position gestellt, Siehe da... auf Seite 3 wirds angezeigt und keine weitere Seite 4 generiert. VIELEN DANK!!!!

**Comment by do-while** [comment]
Dann muss da wohl irgendetwas drin gewesen sein, was die Sortierung durcheinandergebracht hat.
Schön dass es jetzt läuft, danke für die Rückmeldung.
